$(function(){
	$('#bid_no1')
    .show("slide",{direction:"right"},2000)
    .animate({"border-width":"2px","border-color":"red"},100)
    .animate({"border-width":"2px","border-color":"yellow"},100)
    .animate({"border-width":"2px","border-color":"red"},100)
    .animate({"border-width":"2px","border-color":"yellow"},100)
    .animate({"border-width":"2px","border-color":"red"},100)
    .animate({"border-width":"2px","border-color":"yellow"},100)
    .animate({"border-width":"2px","border-color":"red"},100)
    .animate({"border-width":"2px","border-color":"#F7FE2E"},100)
    
    
    $('#bid_no4')
    .animate({"border-width":"2px","border-color":"black"},200)
    .animate({"border-width":"2px","border-color":"E6E6E6"},200)
    .animate({"border-width":"2px","border-color":"black"},200)
    .animate({"border-width":"2px","border-color":"E6E6E6"},200)
    .animate({"border-width":"2px","border-color":"black"},200)
    .animate({"border-width":"2px","border-color":"E6E6E6"},200)
    .animate({"border-width":"2px","border-color":"black"},200)
    .animate({"border-width":"2px","border-color":"E6E6E6"},200)
    .hide("slide",{direction:"down"},2000)
})